---
- name : install httpd
  hosts: localhost
  gather_facts: yes
  become: true
  tasks:
  - name: install httpd
    yum: 
     name: httpd
     state: installed
  - name: install sshd
    yum:
     name: openssh
     state: installed
